BoxLayout:
    orientation: 'vertical'

    BoxLayout:
        orientation: 'horizontal'
        spacing: 15

        TextInput:
            id: number_input
            text: '7'
            font_size: 46
            multiline: False
            size_hint_x: 0.7

        Button:
            text: 'Calculate Square'
            on_release: app.calculate_square(number_input.text)
            size_hint_x: 0.3


